# Generated by Django 2.0.3 on 2018-03-20 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{2}\\d{8,9}')])),
                ('destination', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{2}\\d{8,9}')])),
                ('start_timestamp', models.DateTimeField(null=True)),
                ('end_timestamp', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoredCallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.IntegerField()),
                ('source', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=11)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
