# Generated by Django 2.0.3 on 2018-03-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=11, null=True)),
                ('destination', models.CharField(max_length=11, null=True)),
                ('start_timestamp', models.DateTimeField(null=True)),
                ('end_timestamp', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoredCallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
