# Generated by Django 2.0.3 on 2018-03-20 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedcallevent',
            name='call_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedcallevent',
            name='destination',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedcallevent',
            name='source',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedcallevent',
            name='timestamp',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedcallevent',
            name='type',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='destination',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{2}\\d{8,9}')]),
        ),
        migrations.AlterField(
            model_name='call',
            name='source',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{2}\\d{8,9}')]),
        ),
    ]
